### ISSUE TITLE
请教下docker方式部署

### ISSUE THREAD

**Issue by BadReese** [SpiderClub/haipproxy#13]
用 docker 方式部署在 VPS 上，顺便修改了 setting 里的密码。本地连接的时候发现密码修改没有生效，用默认的 123456 可以连接上。这个是怎么回事呢？ 
另外，获取可用代理列表一直是空的，除了按照 WIKI 里的 docker-compose up 之外，还需要执行其他操作么？

**Comment by ResolveWang** [comment]
如果你说的是redis的密码的话，需要在`docker-compose.yml`的`requirepass`一项中做同步修改。

可用代理列表是空的，不知道你说的空的是各个组件启动了多少时间后为空。如果是开始的几分钟，可能是为空的，一般IP池需要20~60分钟进行预热。

如果是通过Docker启动的，几分钟后，你可以通过
```
import requests
proxies = {'https': 'http://docker_host:3128'}
resp = requests.get('https://httpbin.org/ip', proxies=proxies)
print(resp.text)
```
来检查代理是否生效。

或者连到redis上看，各个存放代理的队列是否有IP。配置文件中有很多重要的信息，请耐心阅读[开发者文档](https://github.com/SpiderClub/haipproxy/blob/master/docs/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8F%82%E6%95%B0%E5%92%8C%E6%84%8F%E4%B9%89.md)，上面有很多关于项目的细节

**Comment by ResolveWang** [comment]
有问题欢迎再提出来

**Comment by BadReese** [comment]
感谢回复，因为一般我都是手动抓的代理跟验证
所以这是我使用的第一个IP池
没想到还需要20分钟+的时间预热

修改docker-compose.yml的配置应该是用docker的人都懂的吧，这点我也欠缺，惭愧~

**Comment by ResolveWang** [comment]
客气。获取可用IP的时候有个策略，可以阅读一下[这篇文档](https://github.com/SpiderClub/haipproxy/blob/master/docs/haipproxy%E6%A0%B8%E5%BF%83%E6%A0%A1%E9%AA%8C%E5%92%8C%E8%B0%83%E5%BA%A6%E7%AD%96%E7%95%A5.md)进行了解

如果你觉得IP列表的IP数量不够，你可以适当放宽`settings.py`中的参数要求，比如
```
#代理客户端将会从Redis中获取分数不小于6的代理IP，settings.py中默认为７
LOWEST_SCORE = 6
```

**Comment by BadReese** [comment]
好的 谢谢

**Comment by tradzero** [comment]
问个问题 当我docker部署之后 我是不是要手动进入容器内执行squid -N -d1 我启动后尝试telnet 看3128端口发现时常是关闭状态 然后看nohup日志发现报错退出了

**Comment by ResolveWang** [comment]
你用docker compose直接会启动所有组件啊，包括squid.  执行 docker-compose up之后你可以在命令行看到squid启动了，也可以docker exec进容器去查看squid是否启动，参照阅读issue1。项目中没对squid用nohup挂起。如果你是自己按自己的方式操作的话，那我也不清楚哦

**Comment by tradzero** [comment]
@ResolveWang 恩 但是就是我这里 默认使用docker-compose up 之后 检查3128端口发现是关闭的 然后才进去docker容器内用nohup启动squid 然后就可以正常使用一段时间 然后过段时间后又发现3128莫名其妙没了 然后检查nohup.log 发现有错误日志
日志大概是
```log
2018/03/10 02:30:23| Configuring Parent 113.116.179.43/808/0
2018/03/10 02:30:23| Finished loading MIME types and icons.
2018/03/10 02:30:23| Accepting HTTP Socket connections at local=[::]:3128 remote=[::] FD 37 flags=9
2018/03/10 02:30:25| Closing HTTP port [::]:3128
2018/03/10 02:30:25| storeDirWriteCleanLogs: Starting...
2018/03/10 02:30:25|   Finished.  Wrote 0 entries.
2018/03/10 02:30:25|   Took 0.00 seconds (  0.00 entries/sec).
```

**Comment by ResolveWang** [comment]
启动squid直接用`service squid start`就好了
另外，不知道你下载的是啥时候的`haipproxy`，建议更新到最新版，之前的脚本中，`squid`确实起不来。

----
你按照这几个步骤来试试？
```
git clone https://github.com/SpiderClub/haipproxy.git
cd haipproxy
vim settings.py # 改为REDIS_HOST = 'redis'
docker-compose build
docker-compose up
```

启动后前台的日志应该是类似这样的
```
haipproxy_1  | 2018/03/10 04:05:31| Store logging disabled
haipproxy_1  | 2018/03/10 04:05:31| DNS Socket created at [::], FD 10
haipproxy_1  | 2018/03/10 04:05:31| DNS Socket created at 0.0.0.0, FD 11
haipproxy_1  | 2018/03/10 04:05:31| Adding nameserver 127.0.0.11 from /etc/resolv.conf
haipproxy_1  | 2018/03/10 04:05:31| Adding ndots 1 from /etc/resolv.conf
haipproxy_1  | 2018/03/10 04:05:31| HTCP Disabled.
haipproxy_1  | 2018/03/10 04:05:31| commBind: Cannot bind socket FD 13 to [::1]: (99) Cannot assign requested address
haipproxy_1  | 2018/03/10 04:05:31| commBind: Cannot bind socket FD 14 to [::1]: (99) Cannot assign requested address
haipproxy_1  | 2018/03/10 04:05:31| ERROR: Failed to create helper child read FD: UDP[::1]
haipproxy_1  | 2018/03/10 04:05:31| Finished loading MIME types and icons.
haipproxy_1  | 2018/03/10 04:05:31| Accepting HTTP Socket connections at local=[::]:3128 remote=[::] FD 12 flags=9
```

等大致3~5分钟后，然后再开一个终端，请求squid代理
```
import requests
proxies = {'https': 'http://127.0.0.1:3128'}
resp = requests.get('https://httpbin.org/ip', proxies=proxies)
print(resp.text)
```


我按上述步骤在Mac和Ubuntu上测试都没问题。Windows不保证项目的稳定性。

如果还是这样，我也不知道为啥了，不知道为啥squid能启动一会儿，就停止。

**Comment by tradzero** [comment]
@ResolveWang 好的 我再试试 谢谢~
