### ISSUE TITLE
Generic package naming - perhaps use a top level package

### ISSUE THREAD

**Issue by samdfonseca** [SpiderClub/haipproxy#15]
Using generic package names (`client, config, crawler, logger, scheduler, utils`) is likely to cause confusion and possibly naming conflicts. When importing them, there's nothing that associates them as being part haipproxy, which can be confusing when out of context. An easy way to handle this would be moving them under a top-level `haipproxy` package, with the following layout:

```
README.md
...
haipproxy/
├── __init__.py
├── client
│   ├── __init__.py
│   └── ...
├── config
│   └── __init__.py
│...
```

**Comment by ResolveWang** [comment]
Thanks for your advice, it sounds reasonable and the code will be refactored in the future
