### ISSUE TITLE
关于IP归属地的支持.....

### ISSUE THREAD

**Issue by LunacyZeus** [SpiderClub/haipproxy#16]
建议作者加入每次ip加入的时候判断归属地的功能,这样我们可以根据IP归属地来输出可用的ip.
推荐一个好的IP归属地查询工具:https://gitee.com/lionsoul/ip2region   (码云的,请放心食用)

**Comment by ResolveWang** [comment]
这个可能在后续会提供支持，现在精力不大够，您要是有时间或者其他用户有时间，可以考虑实现一下，这个功能对于某些场景下还是有很大用处的
