### ISSUE TITLE
Https校验器问题

### ISSUE THREAD

**Issue by BadReese** [SpiderClub/haipproxy#17]
1.请问在校验器里能够拿到当前校验的代理IP么
2.有的代理虽然能够访问https://httpbin.org/ip，但它未必是HTTPS协议的，所以这个校验器是不是有点问题
class HttpsValidator(BaseValidator, ValidatorRedisSpider):
    """This validator check the liveness of https proxy resources"""
    name = 'https'
    urls = [
        'https://httpbin.org/ip',
    ]
    task_queue = TEMP_HTTPS_QUEUE
    score_queue = VALIDATED_HTTPS_QUEUE
    ttl_queue = TTL_HTTPS_QUEUE
    speed_queue = SPEED_HTTPS_QUEUE

**Comment by ResolveWang** [comment]
1.能拿到啊，scrapy response的`meta`属性中
2.什么代理不是https协议的？我不是很明白你的意思。你是不是说，比如`socks5`协议就能访问`https`?然后他就不是https协议了？可能你对校验器的理解和我对它的理解有一些差异。我对它的理解是，只要支持xx的网站的访问，就把它看做是xx校验器。https校验器已经能访问`https://httpbin.org`了，这当然就是https校验器了啊。

为啥我们要去关心它是什么协议呢？我们只需要给用户提供一个高效且透明的调用方式就行了啊。

如果你觉得有什么问题，那么就指出具体的问题或者说说你的具体做法吧，不然我也不知道如何改进哦。还有一点，请不要过度设计哦

**Comment by BadReese** [comment]
emmmmm,你说的也挺对的
另外我发现了个匿名性的问题。虽然用了代理，但httpbin返回的是真实IP。没记错的话，好像文档是说抛弃了透明代理的

**Comment by ResolveWang** [comment]
是抛弃了，还请你确认清楚，http和https的匿名性对于同一个ip来说可能不同。
```
    def parse(self, response):
        proxy = response.meta.get('proxy')
        speed = response.meta.get('speed')
        url = response.url
       # 这里处理ip透明和匿名问题
        transparent = self.is_transparent(response)
        # 如果是匿名ip，直接就返回，不会进入 yield
        if transparent:
            return
        incr = 1 if self.is_ok(response) else '-inf'
        items = self.set_item_queue(url, proxy, self.init_score, incr, speed)
        for item in items:
            yield item
```

我不知道是不是你的用法有问题。明显有个`init` queue就是来干这个事情的。如果你没懂整个流程的话，建议你把文档所有流程梳理清楚。如果真像你这么说的话，测试的时候知乎早把我的ip给封了
