### ISSUE TITLE
0 proxies have been fetched

### ISSUE THREAD

**Issue by fuyifang** [SpiderClub/haipproxy#24]
为什么我现在运行完一个代理都没有了呢？

**Comment by ResolveWang** [comment]
具体如何操作的，我没法猜测你的操作

**Comment by fuyifang** [comment]
就是运行的你的sample代码zhihu_spider

**Comment by fuyifang** [comment]
部分输出:
`crawling resolvewang's user info……
0 proxies have been fetched
Request succeeded! The proxy is {'https': None}
parsing page's HTML……
crawling  resolvewang's followers list……
crawling page 1/35 ……`

**Comment by ResolveWang** [comment]
ip池需要半个小时到一个小时左右预热，不是马上就能用的。具体流程麻烦阅读开发者文档
