### ISSUE TITLE
GFW_PROXY 需要单独设置吗？

### ISSUE THREAD

**Issue by mycrystalgirl** [SpiderClub/haipproxy#25]
**1.GFW_PROXY = 'http://127.0.0.1:8123'**
这里的意思是要单独设置一个可以翻墙的代理吗？难道不能用内置的ip代理池自动抓取吗？

**2.scrapy-splash需要单独启动吗？**
能不能用一个命令启动服务，方便直接单机部署，想集群部署才用多个启动命令。

**3.client.py_cli可以移动位置吗？**
使用其他爬虫框架，如pyspider。想要用内置的py_cli模式，是要把client目录copy到第三方框架路径下吗？或者如何跨目录调用？

目前问题如上，请作者不吝赐教

**Comment by ResolveWang** [comment]
1.部分站点需要翻墙访问，内置的ip池不具有访问google的功能，因为即使它能访问google，也是需要在国外才能，GFW可以检测到你的流量特征，让你的代理请求出不了墙，所以才有了ss这种工具。如果你无法翻墙的话，可以在`rules.py`中设置相关需要翻墙的抓取目标`enable=1`，或者指定启动爬虫的类型，或者任务调度器的类型，具体见[haipproxy中的任务类型和作用](https://github.com/SpiderClub/haipproxy/blob/master/docs/haipproxy%E4%B8%AD%E7%9A%84%E4%BB%BB%E5%8A%A1%E7%B1%BB%E5%9E%8B%E5%92%8C%E4%BD%9C%E7%94%A8.md)

2.需要单独启动。项目中使用它做ajax渲染，这样才保证了代码的高度可复用性。在工程实现和效率两个方面做了一定的权衡

3.可以移动位置。`py_cli`的主要作用是筛选ip，和它交互的是`redis`（代理池），所以你只需要能保证给它提供一个可以访问`redis`的方式就行了。你如果把client拷到别的框架下，你就需要同时考虑实现一个`get_redis_conn`的方法。

目前由于精力原因，没考虑接入每种爬虫框架和编程语言。ip筛选的核心策略在[core.py](https://github.com/SpiderClub/haipproxy/blob/master/client/core.py)和[ProxyFetcher](https://github.com/SpiderClub/haipproxy/blob/master/client/py_cli.py)类中。你可以把这两块代码拷过去，稍微根据报错修改一下就行了

**Comment by mycrystalgirl** [comment]
首先感谢@ResolveWang的回答。1、2、3问题均以明晰。
关于问题3，我也以为client主要就是与redis通信，拉取代理IP。所以将client移动到其他框架内，并import即可。可是按此方法移动后，提示引入了很多其他目录的模块，所以失败了。
另外您在答案中提到的client/core.py文件，我是在release列表中下载的，并没有此文件。
按道理说，client就是起到拉取ip并筛选的作用，完全可以单独移动引入吧。不知道我的理解对不对？

**Comment by ResolveWang** [comment]
你的理解是对的，client就是去筛选ip而已，只不过client筛ip的时候用了一定的策略，和你以往看到的那些开源项目筛ip的方式有一些不同，[这里](https://github.com/SpiderClub/haipproxy/blob/master/docs/haipproxy%E6%A0%B8%E5%BF%83%E6%A0%A1%E9%AA%8C%E5%92%8C%E8%B0%83%E5%BA%A6%E7%AD%96%E7%95%A5.md)是它的策略详细解释

文档都写了，为啥都不读呢？写文档的目的就是让大家了解项目的设计思路和运行流程，但是感觉开发者文档并没多少人看
