### ISSUE TITLE
make配置redis时报错

### ISSUE THREAD

**Issue by Ranco0929** [SpiderClub/haipproxy#28]
![qq 20180322173239](https://user-images.githubusercontent.com/32027961/37762374-107d9a5a-2df7-11e8-8354-8e69763ae3d0.png)

之前gcc：command not found,在网上找了教程把gcc装好了，但现在make配置redis的时候，报了这个错误，能帮我看一下吗？谢啦

**Comment by Ranco0929** [comment]
http://blog.csdn.net/jy0902/article/details/19248299根据这里的教程已经解决问题了

**Comment by ResolveWang** [comment]
嗯嗯，才看到

**Comment by Ranco0929** [comment]
又出了个问题，能看一下吗
![yy nc6s_ y1z9 an_ 6m](https://user-images.githubusercontent.com/32027961/37774358-f12e4cac-2e1a-11e8-9822-e5daa44453b1.png)
新手配置了一个下午

**Comment by Ranco0929** [comment]
这里这个get_redis_conn是不能用pip命令install吗？
Could not find a version that satisfies the requirement get_redis_connection (from versions: )
No matching distribution found for get_redis_connection
pip的时候是这样的

**Comment by Ranco0929** [comment]
@ResolveWang

**Comment by ResolveWang** [comment]
测试代码建议在ide（比如pycharm）中运行，因为路径问题并没做处理
