### ISSUE TITLE
squid模式下，如何区分http和https？

### ISSUE THREAD

**Issue by mycrystalgirl** [SpiderClub/haipproxy#29]
比如用代理访问一个https的网页，会不会轮询到一个http的代理（不支持https）。如果是，有没有解决的办法？

**Comment by ResolveWang** [comment]
麻烦读文档！。。。。。。
文档的设计流程已经说得很清楚了，你要什么，就去相应的队列取！校验器会自己做校验的，你也可以自己编写校验器和 proxy queue，然后从该 proxy queue中取数据。

**Comment by ResolveWang** [comment]
你的理解是对的，client就是去筛选ip而已，只不过client筛ip的时候用了一定的策略，和你以往看到的那些开源项目筛ip的方式有一些不同，[这里](https://github.com/SpiderClub/haipproxy/blob/master/docs/haipproxy%E6%A0%B8%E5%BF%83%E6%A0%A1%E9%AA%8C%E5%92%8C%E8%B0%83%E5%BA%A6%E7%AD%96%E7%95%A5.md)是它的策略详细解释

文档都写了，为啥都不读呢？写文档的目的就是让大家了解项目的设计思路和运行流程，但是感觉开发者文档并没多少人看
