### ISSUE TITLE
启动crawler_booter.py时候出现Unhandled error in Deferred:  

### ISSUE THREAD

**Issue by ColorfulGhost** [SpiderClub/haipproxy#31]
![image](https://user-images.githubusercontent.com/11071219/37886041-293b5f7c-30eb-11e8-8c9f-6039edf31fbe.png)

是哪里的配置出现问题了吗？

**Comment by ResolveWang** [comment]
你查看一下logs文件夹的日志，看看是不是缺少sqlite.so文件或者模块，是的话就需要安装sqlite

**Comment by ColorfulGhost** [comment]
感谢，是sqlite的原因 ， 还有其他好多坑....终于填完了

**Comment by ResolveWang** [comment]
要是代码有问题，你可以贴一下解决方法或者提PR。如果是系统差异引起的，也可以贴出来的。因为个人项目没办法在每种平台上都做测试
