### ISSUE TITLE
如何清空squid的缓存？

### ISSUE THREAD

**Issue by ColorfulGhost** [SpiderClub/haipproxy#32]
因为跑了一些可用性低的ip我想清空squid的缓存，重新跑一遍。
我尝试删除了`squid.conf`文件，restart squid服务，也把服务端和调度器重启了
再次跑的时候发现旧数据几百条ip又存入到了squid.conf里了...

**Comment by ResolveWang** [comment]
你说的缓存是指的`conf`文件中的吗？如果是的话，是不能通过手动清除的，因为筛ip是通过一套算法去redis中取的，你得把redis中相应的ip删了才行。这个算法中会考虑到最近验证时间，要是过了最近验证时间，它就不会取它了。这个也是用squid的弊端，爬虫客户端无法对代理ip质量进行直接的反馈。

所以我建议你如果用python的话，可以使用Python语言代理客户端，它会实时对代理IP的效果进行反馈。如果你不熟悉Python，可以自己按照Python客户端的编写方式写一个客户端，核心算法见`core.py`，细节可以参考开发者文档，里面说了详细的说明

**Comment by ColorfulGhost** [comment]
谢了，我确实对python不熟悉，我会尝试去编写客户端或学习下Python..
