### ISSUE TITLE
docker-compose up 启动异常

### ISSUE THREAD

**Issue by JMwill** [SpiderClub/haipproxy#33]
在执行 `docker-compose up` 时，启动出现错误：

![image](https://user-images.githubusercontent.com/11496449/38080844-2486b184-3375-11e8-917f-c86d95db51b8.png)

这里是执行的 log：[squid.log](https://github.com/SpiderClub/haipproxy/files/1859385/squid.log)

因为使用的是云服务器，配置比较低，如下：

![image](https://user-images.githubusercontent.com/11496449/38081214-0de578a6-3376-11e8-926f-0fa2d47de8f4.png)

我查看过 log 的错误，貌似是无法连接到 Redis 导致的，但是报错信息是无法获取内存，不知道有没有可能是机子内存过小导致的。麻烦查看下是什么问题。

**Comment by ResolveWang** [comment]
建议你以后直接把信息贴出来，传个文件还得下载。。。

你用的是`release`分支的吗？确实是无法连接`redis`。redis启动默认好像需要至少１G的内存，但是看报错貌似又像是`redis`没被docker compose的其它组件识别。

可以尝试单独部署各个组件，先部署redis，看看能不能启动，如果能的话，确认一下你是否下的是realease页面的，master分支可能会在开发，不保证稳定性。

**Comment by JMwill** [comment]
已经选用 release 代码，但是还是一样的问题，我再琢磨一下吧。谢了

**Comment by ResolveWang** [comment]
试试单独部署各个组件吧

**Comment by JMwill** [comment]
单机部署终于成功了，Docker 部署不知道是否是第二点带来的影响，可以尝试一下，以下是总结的经验：

1. 如果你是用了 virtualenv 并且出现 Permission denies 的话，可以尝试 sudo env PATH=$PATH [方括号内是你的命令，如：./run.sh]
2. 安装 squid 之后应该是默认启动的，所以在执行 run.sh 文件的时候会有报错，可以将最后一行注释掉，并清除倒数第二行的 `&` 符号。

**Comment by ResolveWang** [comment]
感谢反馈。
使用单机部署建议手动部署，`run.sh`没在非docker环境下测试过
