### ISSUE TITLE
windows 7 docker compose up报错

### ISSUE THREAD

**Issue by mrwoody3** [SpiderClub/haipproxy#34]
windows平台docker compose up报错，错误代码如下：
pywintypes.error: (2, 'WaitNamedPipe', '\xcf\xb5\xcd\xb3\xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xce\xc4\xbc\xfe\xa1\xa3')
Failed to execute script docker-compose
请问有解决方法么？

**Comment by ResolveWang** [comment]
建议用linux或者mac,精力有限，没办法去win平台做测试和维护

**Comment by mrwoody3** [comment]
好的，看了文档也意识到这个问题了
