### ISSUE TITLE
如何手动更换的代理IP

### ISSUE THREAD

**Issue by yeszao** [SpiderClub/haipproxy#38]
你好，
请问我用`get_proxy()`获取到一个代理IP之后，用着用着不能用了（被网站屏蔽了），这时在代码里面用`delete_proxy()`删掉这个IP，再用`get_proxy()`获取，还是原来到IP呢？
我用到是docker方式部署。

**Comment by yeszao** [comment]
搞定了，用`proxy_feedback('failure', proxy)`可以更换

**Comment by ResolveWang** [comment]
如果用的是默认的IP调度模式，确实需要手动调用`feedback`方法。有啥问题的话，可以参考一下`example`的代码
