### ISSUE TITLE
Auto try anothor ip proxy when the current ip is disabled.

### ISSUE THREAD

**Issue by gaojiuli** [SpiderClub/haipproxy#42]
我的设置: `{'https': '127.0.0.1:3128', 'http': '127.0.0.1:3128'}`
每次访问外网ip都会自动切换，但是有一个问题，如果当前代理ip已经失效或者请求错误，并没有自动尝试切换为可用ip的能力．

我想要的效果是：当我使用127.0.0.1:3128作为代理时，如果后端代理ip失效，自动切换其它代理ip,保证我的应用能收到正确的返回．

**Comment by ResolveWang** [comment]
你好，如果使用 squid 作为代理服务中间件的话，有的时候是不会做错误ip剔除的，这个需求无法通过squid来解决，只能通过 `py_cli.py`来做。具体可以看看 [issue38](https://github.com/SpiderClub/haipproxy/issues/38)
