### ISSUE TITLE
怎么更换httpbin.py

### ISSUE THREAD

**Issue by OccupationName** [SpiderClub/haipproxy#46]
国内好像链接httpbin.org比较困难，今天用httpbin.org验证的时候就出现了
<!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>
导致可用IP数量的下降，应该修改那些配置文件替换 httpbin.org成其他的网址

**Comment by ResolveWang** [comment]
可能是`httpbin.org`对服务器的部署做了修改，`heroku`在国内访问确实很慢，这段时间比较忙，您可以自己找类似的对国内用户有好的服务进行替换

**Comment by OccupationName** [comment]
我的想法是自己安装一个httpbin服务，将httpbin.py里的网址替换为自己的服务器
根据教程
pip install httpbin
pip install gunicorn
gunicorn -b :80 httpbin:app
但是不能使用https
接下来是要安装https证书吗

**Comment by ResolveWang** [comment]
前端加一层nginx就行了，让nginx解析https请求
