### ISSUE TITLE
别的程序里面怎么获取IP

### ISSUE THREAD

**Issue by Sabirjan** [SpiderClub/haipproxy#47]
我想把这个程序当做一个提供代理的服务端，然后别的程序里面调用某个链接来获取IP。
这个怎么实现？

**Comment by ResolveWang** [comment]
自己用flask或者django写个 restful 接口获取就行了，具体注意事项请阅读开发者文档

**Comment by Sabirjan** [comment]
能不能直接Redis里面获取

**Comment by ResolveWang** [comment]
能啊，你读文档和代码吧，里面有细节
