### ISSUE TITLE
crawler start and finish in 1 second

### ISSUE THREAD

**Issue by sherry0429** [SpiderClub/haipproxy#48]
hey, first thank you of your great work,
i have some problem about this repo,

now my machine on aliyun, and status is:
splash: install by docker, run at localhost:8058
squid: install by yum, run at *:3128
and i use pip to install your all requirements 

my python version is 3.6.4

```python
python crawler_booter.py --usage crawler
```

and i see log in logs directory like this:

2018-05-22 16:24:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-05-22 16:24:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-05-22 16:24:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-05-22 16:24:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-05-22 16:24:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 267658),
 'log_count/INFO': 4,
 'memusage/max': 46108672,
 'memusage/startup': 46108672,
 'start_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 242833)}
2018-05-22 16:24:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 269282),
 'log_count/INFO': 4,
 'memusage/max': 46108672,
 'memusage/startup': 46108672,
 'start_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 250614)}
2018-05-22 16:24:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 270711),
 'log_count/INFO': 4,
 'memusage/max': 46309376,
 'memusage/startup': 46309376,
 'start_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 258190)}
2018-05-22 16:24:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 272169),
 'log_count/INFO': 4,
 'memusage/max': 46559232,
 'memusage/startup': 46559232,
 'start_time': datetime.datetime(2018, 5, 22, 8, 24, 19, 265645)}

can you tell me how can i run this? thanks

**Comment by ResolveWang** [comment]
which version did you use? [Release version](https://github.com/SpiderClub/haipproxy/releases) is recommended. The master  is unstable.

**Comment by sherry0429** [comment]
@ResolveWang 
I use release version v0.10

**Comment by ResolveWang** [comment]
There are not many useful messages for giving advice.

1.Can you connect to redis or splash?

2.Your can remove all the log code in this project and run the crawler at the front, so that all errors  will expose. Maybe some critical infos are hidden.

**Comment by sherry0429** [comment]
ok, i have find the question, i run your code on windows and open debug.
my redis have not password and i comment REDIS_PASSWORD option in settings.py so program raise exception, but i can't find it in logs/log on centos.

thanks your quickly response and great work

**Comment by sherry0429** [comment]
i recommend make a default value when setting's option key is empty

**Comment by ResolveWang** [comment]
Thanks for your advice. I'll do that job in next release
