### ISSUE TITLE
添加新的代理IP供应网站

### ISSUE THREAD

**Issue by Flatheadman** [SpiderClub/haipproxy#52]
首先感谢大神们的开源:)
如果想添加新的代理IP供应网站，应该修改哪些配置或者代码呢？
是否考虑添加这个feature呢？毕竟项目提供的这些代理IP供应网站可能难以满足有些特定的需求，比如对某些国外网站的爬取:)

**Comment by ResolveWang** [comment]
首先，你得知道代理IP抓取器包含[四种类型, all_spiders中](https://github.com/SpiderClub/haipproxy/blob/master/haipproxy/crawler/spiders/__init__.py)，四种类型的使用场景你可以看看注释，都写了。然后在[RCRWAL_TASKS](https://github.com/SpiderClub/haipproxy/blob/master/haipproxy/config/rules.py)按这种方式添加就行了，如果你无法提取出公共的解析方式，那么可以像[parse_my_proxy()](https://github.com/SpiderClub/haipproxy/blob/master/haipproxy/crawler/spiders/common_spider.py)方法那样单独写一个解析方法，来解析你要添加的代理IP源，然后把解析的结果入库就行了

**Comment by Flatheadman** [comment]
非常清楚了！感谢大神！
