### ISSUE TITLE
运行crawler_booter.py --usage crawler 提示 no module scheduler 

### ISSUE THREAD

**Issue by JieZhaoAllen** [SpiderClub/haipproxy#53]
作者源码包导入是有问题吗    运行提示包找不到

**Comment by ResolveWang** [comment]
你用的是不是master分支的？master分支的文档由于精力原因最近没更新，项目主页的文档对应的是[releases](https://github.com/SpiderClub/haipproxy/releases)，建议根据文档使用`release`中的

**Comment by JieZhaoAllen** [comment]
我用的不是master分支  就是releases

**Comment by JieZhaoAllen** [comment]
我再调试下  应该是我的问题
