### ISSUE TITLE
卡在一个地方，获取不到代理ip了

### ISSUE THREAD

**Issue by Hotsunrize** [SpiderClub/haipproxy#55]
没看到什么明显的错误
![log](https://user-images.githubusercontent.com/24307070/41694635-c7db1492-753d-11e8-8b15-b222312067c0.png)

redis里面只有这两个队列

![redis](https://user-images.githubusercontent.com/24307070/41694584-8d5a8a28-753d-11e8-900f-1e64b05eaa79.png)

**Comment by ResolveWang** [comment]
建议别使用 docker-compose, 这种方法我没严格测试，直接使用 virtualenv 进行部署和运行试试，不行再贴详细信息

**Comment by Hotsunrize** [comment]
主要docker部署方便啊，一键搞定，只需要dockerfile就行，高可用，秒级部署，互联网趋势

**Comment by ResolveWang** [comment]
建议你直接按照文档在宿主机上部署看看会不会有问题，应该没什么问题的，有问题再反馈
