### ISSUE TITLE
请问是否支持多线程爬取啊

### ISSUE THREAD

**Issue by liangYe10086** [SpiderClub/haipproxy#56]
想请教一下，当我多线程爬取的时候，一直是0 proxies have been fetched，这说明这个系统不支持多线程爬取吗

**Comment by liangYe10086** [comment]
非常感谢耐心解答，示例代码中的多线程是在get_followers里面吗 我这边主要是想用多线程同时爬取多个url子网页的内容 还请大神多多指教

**Comment by ResolveWang** [comment]
也是可以啊。你那边不行吗？看了Redis中有代理了吗？

我这边目前都还在抓数据呢
