### ISSUE TITLE
请问怎么获取gfw的ip，需要在机器上配置什么gfw工具呢

### ISSUE THREAD

**Issue by SoulMeister** [SpiderClub/haipproxy#64]
你好，我看项目中的gfw_spider是通过127.0.0.1:8123这个端口来提供fanqiang的服务，请问在服务端需要配置什么工具呢，，ss可以吗  有具体的配置方法吗，，我尝试了很多种方法都失败了

**Comment by ResolveWang** [comment]
看看wiki中写的将`socks5`转成`http`协议
点击[wiki](https://github.com/SpiderClub/haipproxy/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%96%87%E6%A1%A3%E7%9B%AE%E5%BD%95)查看
