### ISSUE TITLE
安装都成功，但是一个IP都跑不到；有人碰见么

### ISSUE THREAD

**Issue by jack-ZG** [SpiderClub/haipproxy#71]
![image](https://user-images.githubusercontent.com/13432850/45068046-42915980-b0f8-11e8-9f53-6d100f53108e.png)

2018-09-05 10:29:07 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
Read 0 requests from haipproxy:spider:common
2018-09-05 10:29:07 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
Read 0 requests from haipproxy:spider:ajax
Read 0 requests from haipproxy:spider:common
Read 0 requests from haipproxy:spider:ajax
Read 0 requests from haipproxy:spider:common
Read 0 requests from haipproxy:spider:ajax
Read 0 requests from haipproxy:spider:common
Read 0 requests from haipproxy:spider:ajax

**Comment by ResolveWang** [comment]
你没启动定时任务调度器吧

**Comment by newhwa** [comment]
还没到启动调度那步骤啊

**Comment by newhwa** [comment]
我也是一样的现象， 调度还没到那一步啊。

**Comment by newhwa** [comment]
我也是一样的现象， 调度还没到那一步啊。四个command要都执行吗

**Comment by jack-ZG** [comment]
要必须启动定时任务才能抓取到？
![image](https://user-images.githubusercontent.com/13432850/45280024-70fea280-b505-11e8-995a-7740243b34dd.png)
我只执行了这两个。

**Comment by ResolveWang** [comment]
文档写得很清楚啊
```
启动调度器，包括代理IP定时调度和校验

python scheduler_booter.py --usage crawler

python scheduler_booter.py --usage validator

```
