### ISSUE TITLE
get_available_proxies 方法中有个判断语句好像有问题

### ISSUE THREAD

**Issue by whg517** [SpiderClub/haipproxy#74]
https://github.com/SpiderClub/haipproxy/blob/9e11cdeb71a209f0ec3db05c67351de42acbd7b8/haipproxy/client/core.py#L33
https://github.com/SpiderClub/haipproxy/blob/9e11cdeb71a209f0ec3db05c67351de42acbd7b8/haipproxy/client/core.py#L34

https://github.com/SpiderClub/haipproxy/blob/9e11cdeb71a209f0ec3db05c67351de42acbd7b8/haipproxy/client/core.py#L35
https://github.com/SpiderClub/haipproxy/blob/9e11cdeb71a209f0ec3db05c67351de42acbd7b8/haipproxy/client/core.py#L36

这个判断条件都一样，但是条件内的语句并并不一样。

**Comment by ResolveWang** [comment]
不是一样的，有个校验条件弱化的过程。先是考察池子里的IP是不是满足条件，不满足就弱化到只考虑`ttl`和`speed`，如果这两个交集不满足条件，那么就考虑`ttl`和`scored`的并集

**Comment by whg517** [comment]
get it
