### ISSUE TITLE
蘑菇代理换域名了

### ISSUE THREAD

**Issue by pinple** [SpiderClub/haipproxy#94]
http://www.mogumiao.com/  --->   http://www.moguproxy.com/

**Comment by xinmans** [comment]
嗯… 无法访问此页面www.moguproxy.com 花了太长时间进行响应
请尝试：

你是否指 http://uproxx.com/?
在 web 上搜索 [moguproxy](https://www.bing.com/search?form=ANLKDR&q=moguproxy)
检查连接
[检查代理和防火墙](chrome-error://chromewebdata/#buttons)
[运行 Windows 网络诊断](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT
